spring.application.name=aresApp-backend

# Server Configuration
server.port=8080
server.servlet.context-path=/

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/aresdb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=ares
spring.datasource.password=Ares$0101

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# H2 Console (desativado em PostgreSQL)
spring.h2.console.enabled=false

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=Minha1234567890101Chave1234567890101Secreta1234567890101Minha1234567890101Chave1234567890101Secreta1234567890101
jwt.expiration=86400000

# Logging
logging.level.root=INFO
logging.level.com.example.demo=DEBUG

# Jackson Configuration
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC
